config/routes.rb
RailsDecal::Application.routes.draw do
  root to: "pages#home"

  get "apply", to: "student_applications#new", as: "apply" if Rails.env.development?
  post "apply", to: "student_applications#create", as: "student_applications" if Rails.env.development?
  get "office-hours", to: "pages#office_hours"
  get "why", to: "pages#why"

  devise_for :users, path: "",
                     skip: [:registrations],
                     path_names: {
                       sign_in: "login",
                       sign_out: "logout",
                       sign_up: "sign-up",
                     },
                     controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       sessions: "sessions",
                     }

  resources :absences, only: [:create, :index, :new]
  resources :assignments
  resources :assignment_submissions, only: [:create, :update]
  # resources :lectures, only: [:index, :show]
  resources :student_applications, only: [:create, :new]
  resources :users, only: [:edit, :show, :update] do
    member do
      post "check-in", to: "check_ins#create"
    end
  end

  namespace :admin do
    get "/", to: redirect("/admin/dashboard")
    get "dashboard", to: "pages#dashboard"

    get "student-applications", to: "pages#student_applications", as: "student_applications_per_semester"
    scope "student-applications" do
      scope ":semester_url" do
        get "evaluations", to: "evaluations#index", as: "evaluations"
        resources :student_applications, path: "", only: [:show, :index] do
          member do
            match "evaluate", to: "evaluations#create", as: "evaluate", via: [:patch, :post]
            patch "accept", to: "student_applications#accept", as: "accept"
            patch "pend", to: "student_applications#pend", as: "pend"
          end
        end
      end
    end

    resources :users, only: [:index] do
      collection do
        get "students", to: "users#students"
      end
    end

    resources :check_in_codes, path: "check-in-codes", only: [:index, :show, :new, :create] do
      member do
        post "disable", to: "check_in_codes#disable"
        post "enable",  to: "check_in_codes#enable"
      end
    end

    resources :absences do
      member do
        patch "accept", to: "absences#accept", as: "accept"
        patch "reject", to: "absences#reject", as: "reject"
      end
    end
    resources :semesters, only: [:create, :new, :show]
    resources :assignments, only: [:index, :show]
    resources :assignment_submissions, only: [:show, :update]
  end

  get "*path", to: "pages#error", as: "error_page"
end

app/views/admin/pages/dashboard.html.slim
= provide :title, "Admin Dashboard"

.container
  .row
    .col-md-12
      h1 Admin Dashboard
      .row
        .col-md-6
          = link_to "All Users", admin_users_path, class: "flat-button"
        .col-md-6
          = link_to "Current Students", students_admin_users_path, class: "flat-button"
        .col-md-6
          = link_to "All Student Applications", admin_student_applications_per_semester_path, class: "flat-button"
        .col-md-6
          = link_to "Current Assignments", admin_assignments_path, class: "flat-button"
        .col-md-6
          - if current_user.is_current_instructor?
            = link_to "New Semester", new_admin_semester_path, class: "flat-button"
        .col-md-6
          = link_to "Absence Requests", admin_absences_path, class: "flat-button"

      .row
        .col-md-6
          = link_to "Check In Codes", admin_check_in_codes_path, class: "flat-button"

app/views/admin/pages/student_applications.html.slim
= provide :title, "Student Applications"

.container
  .row
    .col-md-12
      h1 Student Applications
      .row
        .col-md-12
          - Semester.all.each do |semester|
            .semester-link
              = link_to semester.name, admin_student_applications_path(semester_url: semester.url), class: "flat-button"