config/routes.rb
RailsDecal::Application.routes.draw do
  root to: "pages#home"

  get "apply", to: "student_applications#new", as: "apply" if Rails.env.development?
  post "apply", to: "student_applications#create", as: "student_applications" if Rails.env.development?
  get "office-hours", to: "pages#office_hours"
  get "why", to: "pages#why"

  devise_for :users, path: "",
                     skip: [:registrations],
                     path_names: {
                       sign_in: "login",
                       sign_out: "logout",
                       sign_up: "sign-up",
                     },
                     controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       sessions: "sessions",
                     }

  resources :absences, only: [:create, :index, :new]
  resources :assignments
  resources :assignment_submissions, only: [:create, :update]
  # resources :lectures, only: [:index, :show]
  resources :student_applications, only: [:create, :new]
  resources :users, only: [:edit, :show, :update] do
    member do
      post "check-in", to: "check_ins#create"
    end
  end

  namespace :admin do
    get "/", to: redirect("/admin/dashboard")
    get "dashboard", to: "pages#dashboard"

    get "student-applications", to: "pages#student_applications", as: "student_applications_per_semester"
    scope "student-applications" do
      scope ":semester_url" do
        get "evaluations", to: "evaluations#index", as: "evaluations"
        resources :student_applications, path: "", only: [:show, :index] do
          member do
            match "evaluate", to: "evaluations#create", as: "evaluate", via: [:patch, :post]
            patch "accept", to: "student_applications#accept", as: "accept"
            patch "pend", to: "student_applications#pend", as: "pend"
          end
        end
      end
    end

    resources :users, only: [:index] do
      collection do
        get "students", to: "users#students"
      end
    end

    resources :check_in_codes, path: "check-in-codes", only: [:index, :show, :new, :create] do
      member do
        post "disable", to: "check_in_codes#disable"
        post "enable",  to: "check_in_codes#enable"
      end
    end

    resources :absences do
      member do
        patch "accept", to: "absences#accept", as: "accept"
        patch "reject", to: "absences#reject", as: "reject"
      end
    end
    resources :semesters, only: [:create, :new, :show]
    resources :assignments, only: [:index, :show]
    resources :assignment_submissions, only: [:show, :update]
  end

  get "*path", to: "pages#error", as: "error_page"
end

app/models/student_application.rb
# == Schema Information
#
# Table name: student_applications
#
#  id                        :integer          not null, primary key
#  first_name                :string
#  last_name                 :string
#  email                     :string
#  phone_number              :string
#  year                      :string
#  major                     :string
#  gpa                       :string
#  why_join                  :text
#  cs_classes_taken          :text
#  current_courseload        :text
#  other_commitments         :text
#  how_did_you_hear_about_us :text
#  how_many_hours_willing    :text
#  created_at                :datetime
#  updated_at                :datetime
#  user_id                   :integer
#  semester_id               :integer
#  standing                  :integer          default(0)
#  status                    :integer          default(0)
#  student_id                :string
#  semesters_applied_before  :text
#

class StudentApplication < ActiveRecord::Base
  include StandingEnum

  scope :current, -> { where(semester: Semester.current) }

  enum status: [ :pending, :accepted, :rejected, :waitlisted ]

  belongs_to :user
  belongs_to :semester

  after_create :update_student_id

  has_many :evaluations, dependent: :destroy

  validates_presence_of :first_name, :last_name, :email, :student_id, :year, :standing,
                        :major, :why_join, :cs_classes_taken, :current_courseload,
                        :other_commitments, :how_many_hours_willing, :how_did_you_hear_about_us,
                        :semesters_applied_before

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  def name
    "#{first_name} #{last_name}"
  end

  def next
    # Returns nil if it cannot find the next application.
    StudentApplication.find_by_id(id + 1)
  end

  def save_and_update_user
    save && user.update(standing: standing)
  end

  def evaluations_by_users(users)
    sorted_evaluations = []
    users.each do |user|
      evaluation = evaluations.find_by_user_id(user.id)
      sorted_evaluations.push(evaluation)
    end
    sorted_evaluations
  end

  # Evaluation totals
  def total(decision)
    evaluations.where(decision: decision).count
  end

  def total_yes
    total('yes')
  end

  def total_maybe
    total('maybe')
  end

  def total_no
    total('no')
  end

  def total_accepted_in_standing
    semester.accepted_student_applications.send(standing).count
  end

  def limit_for_standing
    if standing == "upperclassman"
      semester.upper_division_limit
    else
      semester.lower_division_limit
    end
  end

  def accept
    if total_accepted_in_standing < limit_for_standing
      accepted!
    end
    accepted?
  end

  def pend
    pending!
    pending?
  end

  def update_student_id
    self.user.update(student_id: self.student_id)
  end

end

app/controllers/admin/student_applications_controller.rb
class Admin::StudentApplicationsController < Admin::BaseController
  before_filter :semester
  before_filter :student_applications, only: [:index]
  before_filter :student_application, only: [:show, :accept, :pend]

  def index
    respond_to do |format|
      format.html
      format.csv { send_data StudentApplicationCsv.to_csv @student_applications }
    end
  end

  def show
    evaluations = @student_application.evaluations
    @evaluation = evaluations.find_by_user_id(current_user.id) || evaluations.build
  end

  def accept
    if student_application.accept
      flash[:accept] = "Accepted #{student_application.first_name}"
    else
      flash[:error] = "Max occupancy has been reached"
    end
    next_application
  end

  def pend
    if student_application.pend
      flash[:accept] = "Pended #{student_application.first_name}"
    else
      flash[:error] = "Error occurred"
    end
    next_application
  end

  private

  def student_applications
    @student_applications = StudentApplication.current
    @application_size = @student_applications.size
    @pending = @student_applications.pending
    upperclassmen = @student_applications.upperclassman
    lowerclassmen = @student_applications.lowerclassman
    @accepted_upperclassmen = upperclassmen.accepted
    @accepted_lowerclassmen = lowerclassmen.accepted
    @waitlisted_upperclassmen = upperclassmen.waitlisted
    @waitlisted_lowerclassmen = lowerclassmen.waitlisted
    @rejected = @student_applications.rejected
  end

  def student_application
    @student_application = StudentApplication.find(params[:id])
  end

  def semester
    @semester = Semester.find_by(url: params[:semester_url])
  end

  def next_application
    semester_url = student_application.semester.url

    if student_application.next.nil?
      redirect_to admin_student_applications_path(semester_url: semester_url)
    else
      redirect_to admin_student_application_path(semester_url: semester_url, id: student_application.next.id)
    end
  end

end

app/controllers/student_applications_controller.rb
class StudentApplicationsController < ApplicationController
  load_and_authorize_resource

  def new
    @student_application = StudentApplication.new
  end

  def create
    @student_application = StudentApplication.new(student_application_params)
    @student_application.user = current_user
    @student_application.semester = Semester.current
    if @student_application.save_and_update_user
      flash[:info] = "Thanks for applying! We will get back to you as soon as possible."
      #ApplicationSubmissionMailer.delay.send_confirmation(@student_application.id) patch fix mailer.
      redirect_to why_path
    else
      flash[:danger] = "There was an error submitting your application. Please fix it and try again."
      render 'new'
    end
  end

  private

  def student_application_params
    params.require(:student_application).permit(
      :first_name, :last_name, :email, :student_id, :year, :standing,
      :major, :why_join, :cs_classes_taken, :current_courseload,
      :other_commitments, :how_many_hours_willing, :how_did_you_hear_about_us,
      :semesters_applied_before
    )
  end

end

app/views/student_applications/_apply.html.slim
- if signed_in?
  - if current_user.submitted_current_semester_application?
    p
      | You have already submitted your app for this semester!
  / - else
  /   = link_to "Apply Now!", apply_path, class: "flat-button full-width"
- else
  = link_to "First, Sign in with GitHub", user_omniauth_authorize_path(:github), class: "flat-button full-width"

app/views/student_applications/index.html.slim
.container
  .row
    .col-md-12
      = link_to "Evaluations", evaluations_path
      h1 All Student Applications
      table.table.table-striped
        th Name
        th Email
        th Year
        th Major
        th Turn in Date
        - @student_applications.each do |student_application|
          tr
            td = link_to student_application.name, student_application_path(student_application)
            td = student_application.email
            td = student_application.year
            td = student_application.major
            td = student_application.created_at.to_formatted_s(:long_ordinal)

app/views/student_applications/new.html.slim
= provide :title, "Apply"

.main
  .container
    .row
      .col-md-12
        h1 Student Application
        - if current_user.submitted_current_semester_application?
          .row
            .col-md-12
              h4 = "Thanks for applying, you'll hear back by #{ Semester.current.formatted_acceptance_release_date }."
              p
                ' Please email
                a href="mailto:railsdecal@gmail.com" the staff
                |  if you have any problems or questions.
        - else
          .row
            .col-md-6
              = simple_form_for(@student_application, html: {class: 'form-vertical'}) do |f|
                = f.error_notification
                .form-inputs
                  = f.input :first_name, input_html: { value: current_user.first_name }
                  = f.input :last_name, input_html: { value: current_user.last_name }
                  = f.input :email, input_html: { value: current_user.email }
                  = f.input :student_id, as: :string, label: "Student ID", input_html: { value: current_user.student_id } 
                  = f.input :year, label: "What year will you be in #{ Semester.current.name }?", collection: [['Freshman', 'Freshman'], ['Sophomore','Sophomore'], ['Junior','Junior'], ['Senior','Senior'], ['Fifth Year','Fifth Year']]
                  = f.input :standing, label: "Standing based off units. (You can be a Freshman with Junior standing if you have enough units).", collection: [["Lowerclassman", "lowerclassman"], ["Upperclassman", "upperclassman"]]
                  = f.input :major
                  = f.input :why_join, label: "Why do you want to take the Rails DeCal?"
                  = f.input :cs_classes_taken, label: "List all of the CS classes you have taken separated by a comma. Do not include classes you are taking this semseter."
                  = f.input :current_courseload, label: "List all of the classes you are taking this semester (#{ Semester.current.name }, CS and non-CS)."
                  = f.input :other_commitments, label: "Tell us about yourself. What other commitments do you have this semester?"
                  = f.input :how_many_hours_willing, label: "How many hours are you willing to dedicate to this course?"
                  = f.input :semesters_applied_before, label: "Have you applied to the decal previously? List in which semesters you've applied before."
                  = f.input :how_did_you_hear_about_us, label: "How did you hear about us?", collection: [['Facebook', 'Facebook'], ['Friend','Friend'], ['Flyer','Flyer'], ['Decal.org','Decal.org'], ['Rails Decal Staff', 'Rails Decal Staff'], ['Other','Other']]
                .form-actions
                  = f.button :submit, "Submit", class: 'flat-button'
            .col-md-6
              h2 Application Information
              h4 = "Due #{ Semester.current.formatted_application_deadline }, 11:59 pm"
              p
                ' Please email
                a href="mailto:railsdecal@gmail.com" the staff
                |  if you have any problems or questions.

app/views/student_applications/show.html.slim
.container
  .row
    .col-md-12
      h1 = @student_application.name
      table.table.table-striped
        tr
          td Email
          td = @student_application.email
        tr
          td Year
          td = @student_application.year
        tr
          td Major
          td = @student_application.major
        tr
          td Why Join?
          td = @student_application.why_join
        tr
          td CS Classes Taken
          td = @student_application.cs_classes_taken
        tr
          td Current Courseload
          td = @student_application.current_courseload
        tr
          td Other Commitments
          td = @student_application.other_commitments
        tr
          td How many hours willing
          td = @student_application.how_many_hours_willing
        tr
          td How did you hear about us?
          td = @student_application.how_did_you_hear_about_us

    = render partial: "evaluations/evaluation", locals: { application: @student_application, evaluation: @evaluation }